"""add username to users

Revision ID: 0483f5fbd3d7
Revises: c36505c3dcbc
Create Date: 2026-07-22 14:29:12.872996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0483f5fbd3d7'
down_revision: Union[str, Sequence[str], None] = 'c36505c3dcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index('idx_users_username', 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###

    # Backfill username from email local-part for existing users.
    op.execute("""
        UPDATE users
        SET username = lower(substr(email, 1, instr(email, '@') - 1))
        WHERE username IS NULL AND email LIKE '%@%'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
