"""baseline schema

Revision ID: 09cafc3a6469
Revises:
Create Date: 2026-04-29 11:19:28.254385

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09cafc3a6469"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_team_templates",
        sa.Column("team_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("roles", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default_workflow_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("default_skills", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("runtime_profile_prefs", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_builtin", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("team_id"),
    )
    op.create_index("idx_agent_team_templates_builtin", "agent_team_templates", ["is_builtin"], unique=False)
    op.create_index("idx_agent_team_templates_enabled", "agent_team_templates", ["is_enabled"], unique=False)
    op.create_table(
        "agents",
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("system_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_table(
        "compaction_hints",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scope_layer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scope_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("policy", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trigger_count", sa.Integer(), nullable=False),
        sa.Column("fired_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_compaction_scope", "compaction_hints", ["scope_layer", "scope_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title_source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title_generated_at", sa.DateTime(), nullable=True),
        sa.Column("runtime_profile_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("runtime_instance_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("promoted_project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_conversations_updated_at", "conversations", ["updated_at"], unique=False)
    op.create_table(
        "event_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("situation_tag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dispatched_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action_proposal_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("supervisor_decision", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_event_log_timestamp", "event_log", ["timestamp"], unique=False)
    op.create_table(
        "llm_providers",
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key_encrypted", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_enabled", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("provider_id"),
    )
    op.create_index("idx_llm_providers_default", "llm_providers", ["is_default"], unique=False)
    op.create_index("idx_llm_providers_enabled", "llm_providers", ["is_enabled"], unique=False)
    op.create_table(
        "memory_entries",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("layer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scope_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("last_writer_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("layer", "scope_id", "key"),
    )
    op.create_index("idx_memory_layer_key", "memory_entries", ["layer", "scope_id", "key"], unique=False)
    op.create_index("idx_memory_scope", "memory_entries", ["layer", "scope_id"], unique=False)
    op.create_table(
        "runtime_models",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key_env_var", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("supports_vision", sa.Integer(), nullable=False),
        sa.Column("supports_thinking", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index("idx_runtime_models_enabled", "runtime_models", ["enabled"], unique=False)
    op.create_index("idx_runtime_models_source", "runtime_models", ["source"], unique=False)
    op.create_table(
        "session_promotions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_layer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_scope_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_filter", sa.JSON(), nullable=True),
        sa.Column("promoted_at", sa.DateTime(), nullable=True),
        sa.Column("snapshot_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "working_memory",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain_tags", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_writer_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index("idx_working_memory_tags", "working_memory", ["domain_tags"], unique=False)
    op.create_table(
        "action_proposals",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_resource", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("preconditions", sa.JSON(), nullable=True),
        sa.Column("postconditions", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.agent_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_action_proposals_status", "action_proposals", ["status"], unique=False)
    op.create_table(
        "llm_provider_models",
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("litellm_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("supports_vision", sa.Integer(), nullable=False),
        sa.Column("supports_thinking", sa.Integer(), nullable=False),
        sa.Column("fallback_model_names", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_enabled", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_providers.provider_id"],
        ),
        sa.PrimaryKeyConstraint("provider_id", "model_name"),
    )
    op.create_index("idx_llm_provider_models_enabled", "llm_provider_models", ["is_enabled"], unique=False)
    op.create_index("idx_llm_provider_models_provider", "llm_provider_models", ["provider_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_call_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_messages_conversation", "messages", ["conversation_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("constraints", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("next_step", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("risk_level", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_index("idx_projects_conversation", "projects", ["conversation_id"], unique=False)
    op.create_index("idx_projects_source_conversation", "projects", ["source_conversation_id"], unique=False)
    op.create_index("idx_projects_status", "projects", ["status"], unique=False)
    op.create_table(
        "runtime_model_assignments",
        sa.Column("subject_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_default", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_name"],
            ["runtime_models.name"],
        ),
        sa.PrimaryKeyConstraint("subject_type", "subject_id", "model_name"),
    )
    op.create_index(
        "idx_runtime_model_assignments_subject",
        "runtime_model_assignments",
        ["subject_type", "subject_id"],
        unique=False,
    )
    op.create_table(
        "strategy_change_proposals",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("situation_tag", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("proposed_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("proposed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["proposed_agent_id"],
            ["agents.agent_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategy_table",
        sa.Column("situation_tag", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.agent_id"],
        ),
        sa.PrimaryKeyConstraint("situation_tag"),
    )
    op.create_table(
        "project_agent_team_instances",
        sa.Column("instance_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_template_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instance_config", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_template_id"],
            ["agent_team_templates.team_id"],
        ),
        sa.PrimaryKeyConstraint("instance_id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index("idx_project_team_instances_project", "project_agent_team_instances", ["project_id"], unique=False)
    op.create_index(
        "idx_project_team_instances_template", "project_agent_team_instances", ["team_template_id"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index("idx_runs_conversation", "runs", ["conversation_id"], unique=False)
    op.create_index("idx_runs_project", "runs", ["project_id"], unique=False)
    op.create_index("idx_runs_status", "runs", ["status"], unique=False)
    op.create_table(
        "approval_requests",
        sa.Column("approval_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action_proposal_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("risk_tier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requested_capability", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("impact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("approver_role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recovery_behavior", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("decision_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_proposal_id"],
            ["action_proposals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index("idx_approval_requests_project", "approval_requests", ["project_id"], unique=False)
    op.create_index("idx_approval_requests_risk", "approval_requests", ["risk_tier"], unique=False)
    op.create_index("idx_approval_requests_run", "approval_requests", ["run_id"], unique=False)
    op.create_index("idx_approval_requests_status", "approval_requests", ["status"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("assignee_role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_workstream", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("artifact_ids", sa.JSON(), nullable=True),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index("idx_tasks_project", "tasks", ["project_id"], unique=False)
    op.create_index("idx_tasks_run", "tasks", ["run_id"], unique=False)
    op.create_index("idx_tasks_status", "tasks", ["status"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("artifact_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author_role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("artifact_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    op.create_index("idx_artifacts_conversation", "artifacts", ["conversation_id"], unique=False)
    op.create_index("idx_artifacts_message", "artifacts", ["message_id"], unique=False)
    op.create_index("idx_artifacts_project", "artifacts", ["project_id"], unique=False)
    op.create_index("idx_artifacts_run", "artifacts", ["run_id"], unique=False)
    op.create_index("idx_artifacts_task", "artifacts", ["task_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("audit_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audit_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("approval_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actor_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("decision", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval_requests.approval_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index("idx_audit_logs_approval", "audit_logs", ["approval_id"], unique=False)
    op.create_index("idx_audit_logs_project", "audit_logs", ["project_id"], unique=False)
    op.create_index("idx_audit_logs_run", "audit_logs", ["run_id"], unique=False)
    op.create_index("idx_audit_logs_timestamp", "audit_logs", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_audit_logs_timestamp", table_name="audit_logs")
    op.drop_index("idx_audit_logs_run", table_name="audit_logs")
    op.drop_index("idx_audit_logs_project", table_name="audit_logs")
    op.drop_index("idx_audit_logs_approval", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("idx_artifacts_task", table_name="artifacts")
    op.drop_index("idx_artifacts_run", table_name="artifacts")
    op.drop_index("idx_artifacts_project", table_name="artifacts")
    op.drop_index("idx_artifacts_message", table_name="artifacts")
    op.drop_index("idx_artifacts_conversation", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index("idx_tasks_status", table_name="tasks")
    op.drop_index("idx_tasks_run", table_name="tasks")
    op.drop_index("idx_tasks_project", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("idx_approval_requests_status", table_name="approval_requests")
    op.drop_index("idx_approval_requests_run", table_name="approval_requests")
    op.drop_index("idx_approval_requests_risk", table_name="approval_requests")
    op.drop_index("idx_approval_requests_project", table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index("idx_runs_status", table_name="runs")
    op.drop_index("idx_runs_project", table_name="runs")
    op.drop_index("idx_runs_conversation", table_name="runs")
    op.drop_table("runs")
    op.drop_index("idx_project_team_instances_template", table_name="project_agent_team_instances")
    op.drop_index("idx_project_team_instances_project", table_name="project_agent_team_instances")
    op.drop_table("project_agent_team_instances")
    op.drop_table("strategy_table")
    op.drop_table("strategy_change_proposals")
    op.drop_index("idx_runtime_model_assignments_subject", table_name="runtime_model_assignments")
    op.drop_table("runtime_model_assignments")
    op.drop_index("idx_projects_status", table_name="projects")
    op.drop_index("idx_projects_source_conversation", table_name="projects")
    op.drop_index("idx_projects_conversation", table_name="projects")
    op.drop_table("projects")
    op.drop_index("idx_messages_conversation", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_llm_provider_models_provider", table_name="llm_provider_models")
    op.drop_index("idx_llm_provider_models_enabled", table_name="llm_provider_models")
    op.drop_table("llm_provider_models")
    op.drop_index("idx_action_proposals_status", table_name="action_proposals")
    op.drop_table("action_proposals")
    op.drop_index("idx_working_memory_tags", table_name="working_memory")
    op.drop_table("working_memory")
    op.drop_table("session_promotions")
    op.drop_index("idx_runtime_models_source", table_name="runtime_models")
    op.drop_index("idx_runtime_models_enabled", table_name="runtime_models")
    op.drop_table("runtime_models")
    op.drop_index("idx_memory_scope", table_name="memory_entries")
    op.drop_index("idx_memory_layer_key", table_name="memory_entries")
    op.drop_table("memory_entries")
    op.drop_index("idx_llm_providers_enabled", table_name="llm_providers")
    op.drop_index("idx_llm_providers_default", table_name="llm_providers")
    op.drop_table("llm_providers")
    op.drop_index("idx_event_log_timestamp", table_name="event_log")
    op.drop_table("event_log")
    op.drop_index("idx_conversations_updated_at", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("idx_compaction_scope", table_name="compaction_hints")
    op.drop_table("compaction_hints")
    op.drop_table("agents")
    op.drop_index("idx_agent_team_templates_enabled", table_name="agent_team_templates")
    op.drop_index("idx_agent_team_templates_builtin", table_name="agent_team_templates")
    op.drop_table("agent_team_templates")
    # ### end Alembic commands ###
