"""add organization team and user allocations

Revision ID: 10fc37a3d117
Revises: 2489ed793d51
Create Date: 2026-07-22 16:08:23.440741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10fc37a3d117'
down_revision: Union[str, Sequence[str], None] = '2489ed793d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_index('idx_organizations_owner', 'organizations', ['owner_user_id'], unique=False)
    op.create_index('idx_organizations_status', 'organizations', ['status'], unique=False)
    op.create_table('user_allocations',
    sa.Column('allocation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_allowed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_index('idx_user_allocations_user', 'user_allocations', ['user_id'], unique=False)
    op.create_index('idx_user_allocations_user_resource', 'user_allocations', ['user_id', 'resource_type', 'resource_name'], unique=True)
    op.create_table('teams',
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index('idx_teams_organization', 'teams', ['organization_id'], unique=False)
    op.create_index('idx_teams_status', 'teams', ['status'], unique=False)
    op.create_table('team_memberships',
    sa.Column('membership_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index('idx_team_memberships_team', 'team_memberships', ['team_id'], unique=False)
    op.create_index('idx_team_memberships_team_user', 'team_memberships', ['team_id', 'user_id'], unique=True)
    op.create_index('idx_team_memberships_user', 'team_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_team_memberships_user', table_name='team_memberships')
    op.drop_index('idx_team_memberships_team_user', table_name='team_memberships')
    op.drop_index('idx_team_memberships_team', table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index('idx_teams_status', table_name='teams')
    op.drop_index('idx_teams_organization', table_name='teams')
    op.drop_table('teams')
    op.drop_index('idx_user_allocations_user_resource', table_name='user_allocations')
    op.drop_index('idx_user_allocations_user', table_name='user_allocations')
    op.drop_table('user_allocations')
    op.drop_index('idx_organizations_status', table_name='organizations')
    op.drop_index('idx_organizations_owner', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
