"""initial orm migration

Revision ID: 1a3eb1e28e8d
Revises: 
Create Date: 2026-04-14 19:07:16.980395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a3eb1e28e8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('compaction_hints',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_layer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compaction_scope', 'compaction_hints', ['scope_layer', 'scope_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_generated_at', sa.DateTime(), nullable=True),
    sa.Column('runtime_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('runtime_instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_updated_at', 'conversations', ['updated_at'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('situation_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dispatched_agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_proposal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supervisor_decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_log_timestamp', 'event_log', ['timestamp'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_writer_agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer', 'scope_id', 'key')
    )
    op.create_index('idx_memory_layer_key', 'memory_entries', ['layer', 'scope_id', 'key'], unique=False)
    op.create_index('idx_memory_scope', 'memory_entries', ['layer', 'scope_id'], unique=False)
    op.create_table('runtime_models',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_env_var', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supports_vision', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('idx_runtime_models_enabled', 'runtime_models', ['enabled'], unique=False)
    op.create_index('idx_runtime_models_source', 'runtime_models', ['source'], unique=False)
    op.create_table('session_promotions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_layer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_scope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_filter', sa.JSON(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('snapshot_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('working_memory',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_writer_agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_working_memory_tags', 'working_memory', ['domain_tags'], unique=False)
    op.create_table('action_proposals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preconditions', sa.JSON(), nullable=True),
    sa.Column('postconditions', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_proposals_status', 'action_proposals', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_table('runtime_model_assignments',
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_name'], ['runtime_models.name'], ),
    sa.PrimaryKeyConstraint('subject_type', 'subject_id', 'model_name')
    )
    op.create_index('idx_runtime_model_assignments_subject', 'runtime_model_assignments', ['subject_type', 'subject_id'], unique=False)
    op.create_table('strategy_change_proposals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('situation_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposed_agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_table',
    sa.Column('situation_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('situation_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_table')
    op.drop_table('strategy_change_proposals')
    op.drop_index('idx_runtime_model_assignments_subject', table_name='runtime_model_assignments')
    op.drop_table('runtime_model_assignments')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_action_proposals_status', table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_index('idx_working_memory_tags', table_name='working_memory')
    op.drop_table('working_memory')
    op.drop_table('session_promotions')
    op.drop_index('idx_runtime_models_source', table_name='runtime_models')
    op.drop_index('idx_runtime_models_enabled', table_name='runtime_models')
    op.drop_table('runtime_models')
    op.drop_index('idx_memory_scope', table_name='memory_entries')
    op.drop_index('idx_memory_layer_key', table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index('idx_event_log_timestamp', table_name='event_log')
    op.drop_table('event_log')
    op.drop_index('idx_conversations_updated_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_compaction_scope', table_name='compaction_hints')
    op.drop_table('compaction_hints')
    op.drop_table('agents')
    # ### end Alembic commands ###
