"""add project_id to conversations and project_memory table

Revision ID: 2489ed793d51
Revises: f29bb0c764d2
Create Date: 2026-07-22 15:45:14.479774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2489ed793d51'
down_revision: Union[str, Sequence[str], None] = 'f29bb0c764d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_memory',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('project_id', 'key')
    )
    op.create_index('idx_project_memory_project', 'project_memory', ['project_id'], unique=False)
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index('idx_conversations_project', ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_conversations_project_id', 'projects', ['project_id'], ['project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_project_id', type_='foreignkey')
        batch_op.drop_index('idx_conversations_project')
        batch_op.drop_column('project_id')
    op.drop_index('idx_project_memory_project', table_name='project_memory')
    op.drop_table('project_memory')
    # ### end Alembic commands ###
