"""add_project_id_to_artifacts

Revision ID: 781d386409d0
Revises: ef1237b05060
Create Date: 2026-04-27 11:45:54.447955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781d386409d0'
down_revision: Union[str, Sequence[str], None] = 'ef1237b05060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.alter_column('conversation_id',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.create_index('idx_artifacts_project', ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_artifacts_project_id', 'projects', ['project_id'], ['project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_artifacts_project_id', type_='foreignkey')
        batch_op.drop_index('idx_artifacts_project')
        batch_op.alter_column('conversation_id',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.drop_column('project_id')
    # ### end Alembic commands ###
