"""add_project_conversation_id

Revision ID: 8f27dafa0bbc
Revises: 781d386409d0
Create Date: 2026-04-27 11:51:09.249245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f27dafa0bbc'
down_revision: Union[str, Sequence[str], None] = '781d386409d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(), nullable=True))
        batch_op.create_index('idx_projects_conversation', ['conversation_id'], unique=False)
        batch_op.create_foreign_key('fk_projects_conversation_id', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_conversation_id', type_='foreignkey')
        batch_op.drop_index('idx_projects_conversation')
        batch_op.drop_column('conversation_id')
    # ### end Alembic commands ###
