"""drop legacy surfaces

Revision ID: c36505c3dcbc
Revises: e3f4a5b6c7d8
Create Date: 2026-07-22 14:02:14.438313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c36505c3dcbc'
down_revision: Union[str, Sequence[str], None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop foreign-key columns on surviving tables first so dependent tables can be dropped.
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('idx_artifacts_project')
        batch_op.drop_index('idx_artifacts_run')
        batch_op.drop_index('idx_artifacts_task')
        batch_op.drop_column('author_role')
        batch_op.drop_column('run_id')
        batch_op.drop_column('task_id')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('promoted_project_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('run_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_source_conversation')
        batch_op.drop_column('source_conversation_id')

    # Drop legacy tables in dependency order (children before parents).
    op.drop_index(op.f('idx_audit_logs_approval'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_project'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_run'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')

    op.drop_index(op.f('idx_approval_requests_project'), table_name='approval_requests')
    op.drop_index(op.f('idx_approval_requests_risk'), table_name='approval_requests')
    op.drop_index(op.f('idx_approval_requests_run'), table_name='approval_requests')
    op.drop_index(op.f('idx_approval_requests_status'), table_name='approval_requests')
    op.drop_table('approval_requests')

    op.drop_index(op.f('idx_tasks_project'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_run'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_run_step'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_step_key'), table_name='tasks')
    op.drop_table('tasks')

    op.drop_index(op.f('idx_runs_conversation'), table_name='runs')
    op.drop_index(op.f('idx_runs_project'), table_name='runs')
    op.drop_index(op.f('idx_runs_status'), table_name='runs')
    op.drop_table('runs')

    op.drop_index(op.f('idx_project_team_instances_project'), table_name='project_agent_team_instances')
    op.drop_index(op.f('idx_project_team_instances_template'), table_name='project_agent_team_instances')
    op.drop_table('project_agent_team_instances')

    op.drop_index(op.f('idx_agent_team_templates_builtin'), table_name='agent_team_templates')
    op.drop_index(op.f('idx_agent_team_templates_enabled'), table_name='agent_team_templates')
    op.drop_table('agent_team_templates')

    op.drop_index(op.f('idx_action_proposals_status'), table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_table('strategy_change_proposals')
    op.drop_table('strategy_table')
    op.drop_table('agents')

    op.drop_index(op.f('idx_memory_layer_key'), table_name='memory_entries')
    op.drop_index(op.f('idx_memory_scope'), table_name='memory_entries')
    op.drop_table('memory_entries')

    op.drop_index(op.f('idx_event_log_timestamp'), table_name='event_log')
    op.drop_table('event_log')

    op.drop_index(op.f('idx_working_memory_tags'), table_name='working_memory')
    op.drop_table('working_memory')

    op.drop_index(op.f('idx_compaction_scope'), table_name='compaction_hints')
    op.drop_table('compaction_hints')

    op.drop_table('session_promotions')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('source_conversation_id', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'projects', 'conversations', ['source_conversation_id'], ['id'])
    op.create_index(op.f('idx_projects_source_conversation'), 'projects', ['source_conversation_id'], unique=False)
    op.add_column('messages', sa.Column('run_id', sa.VARCHAR(), nullable=True))
    op.add_column('conversations', sa.Column('promoted_project_id', sa.VARCHAR(), nullable=True))
    op.add_column('artifacts', sa.Column('project_id', sa.VARCHAR(), nullable=True))
    op.add_column('artifacts', sa.Column('task_id', sa.VARCHAR(), nullable=True))
    op.add_column('artifacts', sa.Column('run_id', sa.VARCHAR(), nullable=True))
    op.add_column('artifacts', sa.Column('author_role', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'artifacts', 'runs', ['run_id'], ['run_id'])
    op.create_foreign_key(None, 'artifacts', 'projects', ['project_id'], ['project_id'])
    op.create_foreign_key(None, 'artifacts', 'tasks', ['task_id'], ['task_id'])
    op.create_index(op.f('idx_artifacts_task'), 'artifacts', ['task_id'], unique=False)
    op.create_index(op.f('idx_artifacts_run'), 'artifacts', ['run_id'], unique=False)
    op.create_index(op.f('idx_artifacts_project'), 'artifacts', ['project_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('approval_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('action_proposal_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('risk_tier', sa.VARCHAR(), nullable=False),
    sa.Column('requested_capability', sa.VARCHAR(), nullable=True),
    sa.Column('evidence', sa.VARCHAR(), nullable=True),
    sa.Column('impact', sa.VARCHAR(), nullable=True),
    sa.Column('approver_role', sa.VARCHAR(), nullable=True),
    sa.Column('recovery_behavior', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('decision_reason', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('idx_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('idx_approval_requests_run'), 'approval_requests', ['run_id'], unique=False)
    op.create_index(op.f('idx_approval_requests_risk'), 'approval_requests', ['risk_tier'], unique=False)
    op.create_index(op.f('idx_approval_requests_project'), 'approval_requests', ['project_id'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('goal', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('idx_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('idx_runs_project'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('idx_runs_conversation'), 'runs', ['conversation_id'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('goal', sa.VARCHAR(), nullable=False),
    sa.Column('situation_tag', sa.VARCHAR(), nullable=True),
    sa.Column('dispatched_agent_id', sa.VARCHAR(), nullable=True),
    sa.Column('action_proposal_id', sa.VARCHAR(), nullable=True),
    sa.Column('supervisor_decision', sa.VARCHAR(), nullable=True),
    sa.Column('outcome', sa.VARCHAR(), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_event_log_timestamp'), 'event_log', ['timestamp'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('layer', sa.VARCHAR(), nullable=False),
    sa.Column('scope_id', sa.VARCHAR(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('ttl', sa.INTEGER(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('last_writer_agent_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer', 'scope_id', 'key')
    )
    op.create_index(op.f('idx_memory_scope'), 'memory_entries', ['layer', 'scope_id'], unique=False)
    op.create_index(op.f('idx_memory_layer_key'), 'memory_entries', ['layer', 'scope_id', 'key'], unique=False)
    op.create_table('project_agent_team_instances',
    sa.Column('instance_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('team_template_id', sa.VARCHAR(), nullable=False),
    sa.Column('instance_config', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('runtime_profile_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['team_template_id'], ['agent_team_templates.team_id'], ),
    sa.PrimaryKeyConstraint('instance_id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('idx_project_team_instances_template'), 'project_agent_team_instances', ['team_template_id'], unique=False)
    op.create_index(op.f('idx_project_team_instances_project'), 'project_agent_team_instances', ['project_id'], unique=False)
    op.create_table('agent_team_templates',
    sa.Column('team_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('icon', sa.VARCHAR(), nullable=True),
    sa.Column('roles', sa.VARCHAR(), nullable=False),
    sa.Column('default_workflow_id', sa.VARCHAR(), nullable=True),
    sa.Column('default_skills', sa.VARCHAR(), nullable=False),
    sa.Column('runtime_profile_prefs', sa.VARCHAR(), nullable=False),
    sa.Column('is_builtin', sa.INTEGER(), nullable=False),
    sa.Column('is_enabled', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('idx_agent_team_templates_enabled'), 'agent_team_templates', ['is_enabled'], unique=False)
    op.create_index(op.f('idx_agent_team_templates_builtin'), 'agent_team_templates', ['is_builtin'], unique=False)
    op.create_table('compaction_hints',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('scope_layer', sa.VARCHAR(), nullable=False),
    sa.Column('scope_id', sa.VARCHAR(), nullable=False),
    sa.Column('policy', sa.VARCHAR(), nullable=False),
    sa.Column('trigger_count', sa.INTEGER(), nullable=False),
    sa.Column('fired_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_compaction_scope'), 'compaction_hints', ['scope_layer', 'scope_id'], unique=False)
    op.create_table('strategy_table',
    sa.Column('situation_tag', sa.VARCHAR(), nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('success_count', sa.INTEGER(), nullable=False),
    sa.Column('failure_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('situation_tag')
    )
    op.create_table('working_memory',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('domain_tags', sa.VARCHAR(), nullable=True),
    sa.Column('last_writer_agent_id', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('idx_working_memory_tags'), 'working_memory', ['domain_tags'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.VARCHAR(), nullable=False),
    sa.Column('audit_type', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('approval_id', sa.VARCHAR(), nullable=True),
    sa.Column('actor_id', sa.VARCHAR(), nullable=True),
    sa.Column('actor_type', sa.VARCHAR(), nullable=False),
    sa.Column('decision', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.approval_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_logs_run'), 'audit_logs', ['run_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_project'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_approval'), 'audit_logs', ['approval_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('assignee_role', sa.VARCHAR(), nullable=True),
    sa.Column('source_workstream', sa.VARCHAR(), nullable=True),
    sa.Column('artifact_ids', sqlite.JSON(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('step_key', sa.VARCHAR(), nullable=True),
    sa.Column('source_event_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('idx_tasks_step_key'), 'tasks', ['step_key'], unique=False)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_run_step'), 'tasks', ['run_id', 'step_key'], unique=False)
    op.create_index(op.f('idx_tasks_run'), 'tasks', ['run_id'], unique=False)
    op.create_index(op.f('idx_tasks_project'), 'tasks', ['project_id'], unique=False)
    op.create_table('session_promotions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('target_layer', sa.VARCHAR(), nullable=False),
    sa.Column('target_scope_id', sa.VARCHAR(), nullable=False),
    sa.Column('key_filter', sqlite.JSON(), nullable=True),
    sa.Column('promoted_at', sa.DATETIME(), nullable=True),
    sa.Column('snapshot_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_change_proposals',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('situation_tag', sa.VARCHAR(), nullable=False),
    sa.Column('proposed_agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('proposed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['proposed_agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('domain', sa.VARCHAR(), nullable=False),
    sa.Column('system_prompt', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('action_proposals',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('target_resource', sa.VARCHAR(), nullable=True),
    sa.Column('preconditions', sqlite.JSON(), nullable=True),
    sa.Column('postconditions', sqlite.JSON(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_action_proposals_status'), 'action_proposals', ['status'], unique=False)
    # ### end Alembic commands ###
