"""add_projects_table

Revision ID: e4e591a43be1
Revises: ac3d6a9204b0
Create Date: 2026-04-26 17:20:59.528415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4e591a43be1'
down_revision: Union[str, Sequence[str], None] = 'ac3d6a9204b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('idx_projects_source_conversation', 'projects', ['source_conversation_id'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_source_conversation', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
