"""add agent team templates and project team instances

Revision ID: ef1237b05060
Revises: e1f0a2b3c4d5
Create Date: 2026-04-27 11:20:46.403803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1237b05060'
down_revision: Union[str, Sequence[str], None] = 'e1f0a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_team_templates',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('roles', sa.String(), nullable=False),
    sa.Column('default_workflow_id', sa.String(), nullable=True),
    sa.Column('default_skills', sa.String(), nullable=False),
    sa.Column('runtime_profile_prefs', sa.String(), nullable=False),
    sa.Column('is_builtin', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index('idx_agent_team_templates_builtin', 'agent_team_templates', ['is_builtin'], unique=False)
    op.create_index('idx_agent_team_templates_enabled', 'agent_team_templates', ['is_enabled'], unique=False)
    op.create_table('project_agent_team_instances',
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('team_template_id', sa.String(), nullable=False),
    sa.Column('instance_config', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['team_template_id'], ['agent_team_templates.team_id'], ),
    sa.PrimaryKeyConstraint('instance_id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('idx_project_team_instances_project', 'project_agent_team_instances', ['project_id'], unique=False)
    op.create_index('idx_project_team_instances_template', 'project_agent_team_instances', ['team_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_team_instances_template', table_name='project_agent_team_instances')
    op.drop_index('idx_project_team_instances_project', table_name='project_agent_team_instances')
    op.drop_table('project_agent_team_instances')
    op.drop_index('idx_agent_team_templates_enabled', table_name='agent_team_templates')
    op.drop_index('idx_agent_team_templates_builtin', table_name='agent_team_templates')
    op.drop_table('agent_team_templates')
    # ### end Alembic commands ###
