"""add session_type to conversations

Revision ID: f29bb0c764d2
Revises: 0483f5fbd3d7
Create Date: 2026-07-22 14:53:19.771334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f29bb0c764d2'
down_revision: Union[str, Sequence[str], None] = '0483f5fbd3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('session_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###

    # Existing conversations are task sessions.
    op.execute("UPDATE conversations SET session_type = 'task' WHERE session_type IS NULL")

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('session_type', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'session_type')
    # ### end Alembic commands ###
